language: python

install:
- pip install tox

script: tox

jobs:
  include:
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
  - python: '3.8'
    env: TOXENV=py38
  - python: '3.8'
    env: TOXENV=docs
  - python: '3.8'
    env: TOXENV=flake8
  - stage: deploy
    script: echo "Deploying on PyPi ..."
    deploy:
      provider: pypi
      user: JosefFriedrich
      password:
        secure: "emDlf1UH7aob27FtkDescXR0NaEb11WClyzwFQifRzcyayMn3JoNmE47J8DhuIUc+p/neTrVQzewf6rXhT2228PesaVo8fUZ1TcevRslINJUYqoOeQfzK9KVDiy4nwVXdS+SzKMhvohnunHJ7eyDlP9NqHfZOuZSR/Cad4KF62fMonRdhvy3unRIl3lRzStzFjjqFxUEmcYn77L94ABrwBtAYk2OwH6loqTo04wnXJ11JSoXw5GBaGjar4whQVBGTJn7WSzk4ItsyAqkN6fD0q0MOmDNYKsbXQvYqdwdZdgMZdeHnx6bO5gdlRKqh3ctdgpLZe3tSRfVGw4aLFsXdfnVyDrsA48k3H4GTQ2RTQZK3AyupyQv0jXr1/5U341FNf8/66HIigSlnBk9s5PzGgUsh08LV9awP1HU8l/bEoeDCa6Qpq9r9PjVoRxDRKTMuQ7j5yX+mJ3qywkYi3mZHH9m7LIw75W0/AeW8B8XshjxnHL0LkH/P+r0Kxkc6DEy0nAcw7ABd4mMccQspNvgbRhNQS4qdUeRpA7cNJ7oVilNBD+eFIOSeQXg7neLWQWprBJ3SLwI0dTJdNAyPyLEKSJKXUAG1Qhx0PR4Mu+H1/Q+CTEk2OJ1eEFDaxtzHl78qVCNU06rliNbEMqyM4Z18mbz26ZRqM+pgrmXvthqP0s="
      on:
        tags: true
