"""
This type stub file was generated by pyright.
"""

def bytes_to_elementtree(bytes_or_file): # -> ElementTree:
      """Given a bytestring or a file-like object that will produce them,
	parse and return an ElementTree.
	"""
      ...

