"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import

from ansicolor.ansicolor import (
    Colors,
    colordiff,
    colorize,
    colorize_v2,
    get_code,
    get_code_v2,
    get_highlighter,
    highlight_string,
    justify_formatted,
    set_term_title,
    strip_escapes,
    wrap_string,
    write_err,
    write_out,
)

__all__ = [
    "black",
    "blue",
    "cyan",
    "green",
    "magenta",
    "red",
    "white",
    "yellow",
    "colorize",
    "colorize_v2",
    "get_code",
    "get_code_v2",
    "wrap_string",
    "highlight_string",
    "get_highlighter",
    "strip_escapes",
    "justify_formatted",
    "colordiff",
    "set_term_title",
    "write_out",
    "write_err",
    "Colors",
]
__major_version__ = ...
__release__ = ...
__version__ = ...

def black(s: str, bool: bool = ..., reverse: bool = ...) -> str: ...
def blue(s: str, bool: bool = ..., reverse: bool = ...) -> str: ...
def cyan(s: str, bool: bool = ..., reverse: bool = ...) -> str: ...
def green(s: str, bool: bool = ..., reverse: bool = ...) -> str: ...
def magenta(s: str, bool: bool = ..., reverse: bool = ...) -> str: ...
def red(s: str, bool: bool = ..., reverse: bool = ...) -> str: ...
def white(s: str, bool: bool = ..., reverse: bool = ...) -> str: ...
def yellow(s: str, bool: bool = ..., reverse: bool = ...) -> str: ...
