"""
This type stub file was generated by pyright.
"""

def demo_color(): # -> None:
    ...

def demo_color_v2(): # -> None:
    ...

def demo_highlight(): # -> None:
    ...

def demo_highlight_reverse(): # -> None:
    ...

def demo_diff(): # -> None:
    ...

if __name__ == "__main__":
    ...
