"""
This type stub file was generated by pyright.
"""

from tmep import doc, functions, template
from tmep._version import get_versions

__version__ = get_versions()['version']
class Template(template.Template):
    def __init__(self, template) -> None:
        ...
    


class Functions(functions.Functions):
    def __init__(self, values=...) -> None:
        ...
    


def parse(template, values=..., additional_functions=..., functions=...): # -> str:
    ...

