"""
This type stub file was generated by pyright.
"""

from tmep import functions

"""Extract docstrings from func.py to document the template functions."""
Functions = functions.Functions
class Doc:
    def __init__(self) -> None:
        ...
    
    def prepare_docstrings(self, string): # -> str:
        ...
    
    def extract_value(self, string, key, inline_code=...): # -> Any | Literal[False]:
        """Extract strings from the docstrings

        .. code-block:: text

            * synopsis: ``%shorten{text, max_size}``
            * example: ``%shorten{$title, 32}``
            * description: Shorten “text” on word boundarys.

        """
        ...
    
    def underline(self, text, indent=...):
        """Underline a given text"""
        ...
    
    def format(self, text, width=..., indent=...): # -> str:
        """Apply textwrap to a given text string"""
        ...
    
    def get(self): # -> Literal['']:
        """Retrieve a formated text string"""
        ...
    


