"""
This type stub file was generated by pyright.
"""

from mediafile import MediaFile
from typing import Generator

class MediaFileExtended(MediaFile):
    @classmethod
    def fields(cls) -> Generator[str, None, None]:
        """Get the names of all writable properties that reflect
        metadata tags (i.e., those that are instances of
        :class:`MediaField`).
        """
        ...
    
    @classmethod
    def readable_fields(cls) -> Generator[str, None, None]:
        """Get all metadata fields: the writable ones from
        :meth:`fields` and also other audio properties.
        """
        ...
    
    albumartist_sort = ...
    composer_sort = ...
    mb_workid = ...
    mb_workhierarchy_ids = ...
    work = ...
    work_hierarchy = ...
    releasegroup_types = ...


